services:
  # Web service for the Node.js application
  - type: web
    name: zeyadmath-platform
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 18.17.0
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: zeyadmath-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: PORT
        value: 3000
    healthCheckPath: /api/health
    autoDeploy: true

databases:
  # PostgreSQL database
  - name: zeyadmath-db
    plan: free
    databaseName: zeyadmath_production
    user: zeyadmath